// Export pages
export '/pages/feed/feed_widget.dart' show FeedWidget;
export '/pages/painel/painel_widget.dart' show PainelWidget;
export '/pages/avalia/avalia_widget.dart' show AvaliaWidget;
export '/pages/historico/historico_widget.dart' show HistoricoWidget;
export '/pages/ranking/ranking_widget.dart' show RankingWidget;
export '/pages/photo_detail/photo_detail_widget.dart' show PhotoDetailWidget;
export '/pages/plans/plans_widget.dart' show PlansWidget;
export '/pages/plans_asaas/plans_asaas_widget.dart' show PlansAsaasWidget;
export '/pages/reset_password/reset_password_widget.dart' show ResetPasswordWidget;
export '/pages/perfil/perfil_widget.dart' show PerfilWidget;
export '/pages/tutorial_suporte/tutorial_suporte_widget.dart' show TutorialSuporteWidget;
export '/pages/conquistas/conquistas_widget.dart' show ConquistasWidget;
export '/pages/inspirar/inspirar_widget.dart' show InspirarWidget;
export '/pages/reports/reports_widget.dart' show ReportsWidget;
export '/pages/privacy/privacy_widget.dart' show PrivacyWidget;
export '/pages/terms/terms_widget.dart' show TermsWidget;
export '/login/login_widget.dart' show LoginWidget;
export '/signup/signup_widget.dart' show SignupWidget;
