CREATE TABLE ad_configuration (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  banner_ad_unit_id_android text,
  banner_ad_unit_id_ios text,
  interstitial_ad_unit_id_android text,
  interstitial_ad_unit_id_ios text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE ad_configuration ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read" ON ad_configuration
  FOR SELECT USING (true);

INSERT INTO ad_configuration (
  banner_ad_unit_id_android, banner_ad_unit_id_ios,
  interstitial_ad_unit_id_android, interstitial_ad_unit_id_ios
) VALUES (
  'ca-app-pub-3940256099942544/6300978111',
  'ca-app-pub-3940256099942544/2934735716',
  'ca-app-pub-3940256099942544/1033173712',
  'ca-app-pub-3940256099942544/4411468910'
);
